import React from "react";
import Link from "next/link";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

function About() {
  function getRandomInt(count) {
    return Math.floor(Math.random() * count);
  }
  const random = getRandomInt(2);

  if (random == 1) {
    throw new Error("Error Loading About Page");
  }

  return (
    <div>
      <p>About</p>
      <Link href={"/about/part1"} replace>
        Part1
      </Link>
      <Link href={"/about/part1"}>Part1</Link>
    </div>
  );
}

export default About;
