import React from "react";
import Link from "next/link";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

function About() {
  return (
    <div>
      <p>About</p>
      <Link href={"/about/part1"} replace>
        Part1
      </Link>
      <Link href={"/about/part1"}>Part1</Link>
    </div>
  );
}

export default About;
